import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font"; // Correct import for Geist fonts
import "./globals.css";
import { ThemeProvider } from "@/components/ThemesProvider";

const geistSans = GeistSans; // Directly use the imported font object
const geistMono = GeistMono; // Directly use the imported font object

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning> {/* Added lang and suppressHydrationWarning */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system" // Changed defaultTheme to system for better user experience
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}